language: node_js
cache: yarn

node_js:
  - '12'
  - '10'

script: yarn test && yarn travis:coveralls

jobs:
  include:
    - stage: deploy
      name: 'Deploy packages'
      node_js: 12
      if: (NOT type IN (pull_request)) AND (branch = production)
      script: yarn semantic-release && yarn docs:publish

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
